import 'package:flutter/material.dart';

class AppThemes {
  static final allThemes = <String, ThemeData>{
    'Light': ThemeData.light().copyWith(
      cardColor: Colors.grey.shade100,
      dividerColor: Colors.grey.shade300,
      hintColor: Colors.grey.shade600,
    ),
    'Dark': ThemeData.dark().copyWith(
      cardColor: Colors.grey.shade800,
      dividerColor: Colors.grey.shade600,
      hintColor: Colors.grey.shade400,
    ),

    'Cyberpunk': ThemeData(
      brightness: Brightness.dark,
      scaffoldBackgroundColor: const Color(0xFF0D0D0D),
      primaryColor: const Color(0xFFBD93F9),
      cardColor: const Color(0xFF1A1A1A),
      dividerColor: const Color(0xFF44475A),
      hintColor: const Color(0xFF6272A4),
      colorScheme: const ColorScheme.dark(
        primary: Color(0xFFBD93F9),
        secondary: Color(0xFFFFB86C),
        surface: Color(0xFF1A1A1A),
        background: Color(0xFF0D0D0D),
        onPrimary: Colors.black,
        onSecondary: Colors.black,
        onSurface: Color(0xFFF8F8F2),
        onBackground: Color(0xFFF8F8F2),
      ),
      appBarTheme: const AppBarTheme(
        backgroundColor: Color(0xFF44475A),
        foregroundColor: Color(0xFFF8F8F2),
      ),
      textTheme: const TextTheme(
        bodyLarge: TextStyle(color: Color(0xFFF8F8F2)),
        bodyMedium: TextStyle(color: Color(0xFFF8F8F2)),
        bodySmall: TextStyle(color: Color(0xFF6272A4)),
      ),
      iconTheme: const IconThemeData(color: Color(0xFFBD93F9)),
    ),

    'Cupcake': ThemeData(
      brightness: Brightness.light,
      scaffoldBackgroundColor: const Color(0xFFFFF1F5),
      primaryColor: const Color(0xFF65C3C8),
      cardColor: const Color(0xFFFFE4E9),
      dividerColor: const Color(0xFFEF9FBC),
      hintColor: const Color(0xFF8B5A6B),
      colorScheme: const ColorScheme.light(
        primary: Color(0xFF65C3C8),
        secondary: Color(0xFFEF9FBC),
        surface: Color(0xFFFFE4E9),
        background: Color(0xFFFFF1F5),
        onPrimary: Colors.white,
        onSecondary: Colors.white,
        onSurface: Color(0xFF2D1B20),
        onBackground: Color(0xFF2D1B20),
      ),
      appBarTheme: const AppBarTheme(
        backgroundColor: Color(0xFF65C3C8),
        foregroundColor: Colors.white,
      ),
      textTheme: const TextTheme(
        bodyLarge: TextStyle(color: Color(0xFF2D1B20)),
        bodyMedium: TextStyle(color: Color(0xFF2D1B20)),
        bodySmall: TextStyle(color: Color(0xFF8B5A6B)),
      ),
      iconTheme: const IconThemeData(color: Color(0xFF65C3C8)),
    ),

    'Emerald': ThemeData(
      brightness: Brightness.light,
      scaffoldBackgroundColor: const Color(0xFFF0FDF4),
      primaryColor: const Color(0xFF059669),
      cardColor: const Color(0xFFDCFCE7),
      dividerColor: const Color(0xFF86EFAC),
      hintColor: const Color(0xFF166534),
      colorScheme: const ColorScheme.light(
        primary: Color(0xFF059669),
        secondary: Color(0xFF10B981),
        surface: Color(0xFFDCFCE7),
        background: Color(0xFFF0FDF4),
        onPrimary: Colors.white,
        onSecondary: Colors.white,
        onSurface: Color(0xFF064E3B),
        onBackground: Color(0xFF064E3B),
      ),
      appBarTheme: const AppBarTheme(
        backgroundColor: Color(0xFF059669),
        foregroundColor: Colors.white,
      ),
      textTheme: const TextTheme(
        bodyLarge: TextStyle(color: Color(0xFF064E3B)),
        bodyMedium: TextStyle(color: Color(0xFF064E3B)),
        bodySmall: TextStyle(color: Color(0xFF166534)),
      ),
      iconTheme: const IconThemeData(color: Color(0xFF059669)),
    ),

    'Valentine': ThemeData(
      brightness: Brightness.light,
      scaffoldBackgroundColor: const Color(0xFFFDF2F8),
      primaryColor: const Color(0xFFEC4899),
      cardColor: const Color(0xFFFCE7F3),
      dividerColor: const Color(0xFFF9A8D4),
      hintColor: const Color(0xFF9D174D),
      colorScheme: const ColorScheme.light(
        primary: Color(0xFFEC4899),
        secondary: Color(0xFFF472B6),
        surface: Color(0xFFFCE7F3),
        background: Color(0xFFFDF2F8),
        onPrimary: Colors.white,
        onSecondary: Colors.white,
        onSurface: Color(0xFF831843),
        onBackground: Color(0xFF831843),
      ),
      appBarTheme: const AppBarTheme(
        backgroundColor: Color(0xFFEC4899),
        foregroundColor: Colors.white,
      ),
      textTheme: const TextTheme(
        bodyLarge: TextStyle(color: Color(0xFF831843)),
        bodyMedium: TextStyle(color: Color(0xFF831843)),
        bodySmall: TextStyle(color: Color(0xFF9D174D)),
      ),
      iconTheme: const IconThemeData(color: Color(0xFFEC4899)),
    ),

    'Forest': ThemeData(
      brightness: Brightness.dark,
      scaffoldBackgroundColor: const Color(0xFF1B2B2A),
      primaryColor: const Color(0xFF3F6240),
      cardColor: const Color(0xFF2D3E2D),
      dividerColor: const Color(0xFF4A5D4A),
      hintColor: const Color(0xFFA3D9A5),
      colorScheme: const ColorScheme.dark(
        primary: Color(0xFF3F6240),
        secondary: Color(0xFFA3D9A5),
        surface: Color(0xFF2D3E2D),
        background: Color(0xFF1B2B2A),
        onPrimary: Colors.white,
        onSecondary: Color(0xFF1B2B2A),
        onSurface: Color(0xFFE8F5E8),
        onBackground: Color(0xFFE8F5E8),
      ),
      appBarTheme: const AppBarTheme(
        backgroundColor: Color(0xFF1C4532),
        foregroundColor: Color(0xFFE8F5E8),
      ),
      textTheme: const TextTheme(
        bodyLarge: TextStyle(color: Color(0xFFE8F5E8)),
        bodyMedium: TextStyle(color: Color(0xFFE8F5E8)),
        bodySmall: TextStyle(color: Color(0xFFA3D9A5)),
      ),
      iconTheme: const IconThemeData(color: Color(0xFF3F6240)),
    ),

    'Lofi': ThemeData(
      brightness: Brightness.light,
      scaffoldBackgroundColor: const Color(0xFFF9FAFB),
      primaryColor: const Color(0xFF374151),
      cardColor: const Color(0xFFF3F4F6),
      dividerColor: const Color(0xFFD1D5DB),
      hintColor: const Color(0xFF6B7280),
      colorScheme: const ColorScheme.light(
        primary: Color(0xFF374151),
        secondary: Color(0xFF6B7280),
        surface: Color(0xFFF3F4F6),
        background: Color(0xFFF9FAFB),
        onPrimary: Colors.white,
        onSecondary: Colors.white,
        onSurface: Color(0xFF111827),
        onBackground: Color(0xFF111827),
      ),
      appBarTheme: const AppBarTheme(
        backgroundColor: Color(0xFFF3F4F6),
        foregroundColor: Color(0xFF111827),
      ),
      textTheme: const TextTheme(
        bodyLarge: TextStyle(color: Color(0xFF111827)),
        bodyMedium: TextStyle(color: Color(0xFF111827)),
        bodySmall: TextStyle(color: Color(0xFF6B7280)),
      ),
      iconTheme: const IconThemeData(color: Color(0xFF374151)),
    ),

    'Pastel': ThemeData(
      brightness: Brightness.light,
      scaffoldBackgroundColor: const Color(0xFFFFFBF4),
      primaryColor: const Color(0xFFFFB7B2),
      cardColor: const Color(0xFFFFF0ED),
      dividerColor: const Color(0xFFB4F8C8),
      hintColor: const Color(0xFF8B5A6B),
      colorScheme: const ColorScheme.light(
        primary: Color(0xFFFFB7B2),
        secondary: Color(0xFFB4F8C8),
        surface: Color(0xFFFFF0ED),
        background: Color(0xFFFFFBF4),
        onPrimary: Color(0xFF2D1B20),
        onSecondary: Color(0xFF2D1B20),
        onSurface: Color(0xFF2D1B20),
        onBackground: Color(0xFF2D1B20),
      ),
      appBarTheme: const AppBarTheme(
        backgroundColor: Color(0xFFFFB7B2),
        foregroundColor: Color(0xFF2D1B20),
      ),
      textTheme: const TextTheme(
        bodyLarge: TextStyle(color: Color(0xFF2D1B20)),
        bodyMedium: TextStyle(color: Color(0xFF2D1B20)),
        bodySmall: TextStyle(color: Color(0xFF8B5A6B)),
      ),
      iconTheme: const IconThemeData(color: Color(0xFFFFB7B2)),
    ),

    'Dracula': ThemeData(
      brightness: Brightness.dark,
      scaffoldBackgroundColor: const Color(0xFF282A36),
      primaryColor: const Color(0xFFBD93F9),
      cardColor: const Color(0xFF44475A),
      dividerColor: const Color(0xFF6272A4),
      hintColor: const Color(0xFF6272A4),
      colorScheme: const ColorScheme.dark(
        primary: Color(0xFFBD93F9),
        secondary: Color(0xFFFF79C6),
        surface: Color(0xFF44475A),
        background: Color(0xFF282A36),
        onPrimary: Color(0xFF282A36),
        onSecondary: Color(0xFF282A36),
        onSurface: Color(0xFFF8F8F2),
        onBackground: Color(0xFFF8F8F2),
      ),
      appBarTheme: const AppBarTheme(
        backgroundColor: Color(0xFF44475A),
        foregroundColor: Color(0xFFF8F8F2),
      ),
      textTheme: const TextTheme(
        bodyLarge: TextStyle(color: Color(0xFFF8F8F2)),
        bodyMedium: TextStyle(color: Color(0xFFF8F8F2)),
        bodySmall: TextStyle(color: Color(0xFF6272A4)),
      ),
      iconTheme: const IconThemeData(color: Color(0xFFBD93F9)),
    ),

    'Rose': ThemeData(
      brightness: Brightness.light,
      scaffoldBackgroundColor: const Color(0xFFFFF1F5),
      primaryColor: const Color(0xFFF43F5E),
      cardColor: const Color(0xFFFFE4E9),
      dividerColor: const Color(0xFFFB7185),
      hintColor: const Color(0xFF9F1239),
      colorScheme: const ColorScheme.light(
        primary: Color(0xFFF43F5E),
        secondary: Color(0xFFFB7185),
        surface: Color(0xFFFFE4E9),
        background: Color(0xFFFFF1F5),
        onPrimary: Colors.white,
        onSecondary: Colors.white,
        onSurface: Color(0xFF881337),
        onBackground: Color(0xFF881337),
      ),
      appBarTheme: const AppBarTheme(
        backgroundColor: Color(0xFFF43F5E),
        foregroundColor: Colors.white,
      ),
      textTheme: const TextTheme(
        bodyLarge: TextStyle(color: Color(0xFF881337)),
        bodyMedium: TextStyle(color: Color(0xFF881337)),
        bodySmall: TextStyle(color: Color(0xFF9F1239)),
      ),
      iconTheme: const IconThemeData(color: Color(0xFFF43F5E)),
    ),

    'Aqua': ThemeData(
      brightness: Brightness.light,
      scaffoldBackgroundColor: const Color(0xFFDEF7FF),
      primaryColor: const Color(0xFF00B4D8),
      cardColor: const Color(0xFFCAF0F8),
      dividerColor: const Color(0xFF90E0EF),
      hintColor: const Color(0xFF0077B6),
      colorScheme: const ColorScheme.light(
        primary: Color(0xFF00B4D8),
        secondary: Color(0xFF90E0EF),
        surface: Color(0xFFCAF0F8),
        background: Color(0xFFDEF7FF),
        onPrimary: Colors.white,
        onSecondary: Color(0xFF03045E),
        onSurface: Color(0xFF03045E),
        onBackground: Color(0xFF03045E),
      ),
      appBarTheme: const AppBarTheme(
        backgroundColor: Color(0xFF00B4D8),
        foregroundColor: Colors.white,
      ),
      textTheme: const TextTheme(
        bodyLarge: TextStyle(color: Color(0xFF03045E)),
        bodyMedium: TextStyle(color: Color(0xFF03045E)),
        bodySmall: TextStyle(color: Color(0xFF0077B6)),
      ),
      iconTheme: const IconThemeData(color: Color(0xFF00B4D8)),
    ),

    'Luxury': ThemeData(
      brightness: Brightness.dark,
      scaffoldBackgroundColor: const Color(0xFF181028),
      primaryColor: const Color(0xFFD1C4E9),
      cardColor: const Color(0xFF2A1F3D),
      dividerColor: const Color(0xFF4A3B5C),
      hintColor: const Color(0xFFB39DDB),
      colorScheme: const ColorScheme.dark(
        primary: Color(0xFFD1C4E9),
        secondary: Color(0xFFB39DDB),
        surface: Color(0xFF2A1F3D),
        background: Color(0xFF181028),
        onPrimary: Color(0xFF181028),
        onSecondary: Color(0xFF181028),
        onSurface: Color(0xFFF3E5F5),
        onBackground: Color(0xFFF3E5F5),
      ),
      appBarTheme: const AppBarTheme(
        backgroundColor: Color(0xFF2A1F3D),
        foregroundColor: Color(0xFFF3E5F5),
      ),
      textTheme: const TextTheme(
        bodyLarge: TextStyle(color: Color(0xFFF3E5F5)),
        bodyMedium: TextStyle(color: Color(0xFFF3E5F5)),
        bodySmall: TextStyle(color: Color(0xFFB39DDB)),
      ),
      iconTheme: const IconThemeData(color: Color(0xFFD1C4E9)),
    ),

    'Halloween': ThemeData(
      brightness: Brightness.dark,
      scaffoldBackgroundColor: const Color(0xFF1F2937),
      primaryColor: const Color(0xFFFB923C),
      cardColor: const Color(0xFF374151),
      dividerColor: const Color(0xFF6B7280),
      hintColor: const Color(0xFFF97316),
      colorScheme: const ColorScheme.dark(
        primary: Color(0xFFFB923C),
        secondary: Color(0xFFF97316),
        surface: Color(0xFF374151),
        background: Color(0xFF1F2937),
        onPrimary: Color(0xFF1F2937),
        onSecondary: Color(0xFF1F2937),
        onSurface: Color(0xFFF9FAFB),
        onBackground: Color(0xFFF9FAFB),
      ),
      appBarTheme: const AppBarTheme(
        backgroundColor: Color(0xFF374151),
        foregroundColor: Color(0xFFF9FAFB),
      ),
      textTheme: const TextTheme(
        bodyLarge: TextStyle(color: Color(0xFFF9FAFB)),
        bodyMedium: TextStyle(color: Color(0xFFF9FAFB)),
        bodySmall: TextStyle(color: Color(0xFFF97316)),
      ),
      iconTheme: const IconThemeData(color: Color(0xFFFB923C)),
    ),

    'Synthwave': ThemeData(
      brightness: Brightness.dark,
      scaffoldBackgroundColor: const Color(0xFF2E1065),
      primaryColor: const Color(0xFF8B5CF6),
      cardColor: const Color(0xFF4C1D95),
      dividerColor: const Color(0xFF7C3AED),
      hintColor: const Color(0xFFE879F9),
      colorScheme: const ColorScheme.dark(
        primary: Color(0xFF8B5CF6),
        secondary: Color(0xFFE879F9),
        surface: Color(0xFF4C1D95),
        background: Color(0xFF2E1065),
        onPrimary: Colors.white,
        onSecondary: Color(0xFF2E1065),
        onSurface: Color(0xFFF3E8FF),
        onBackground: Color(0xFFF3E8FF),
      ),
      appBarTheme: const AppBarTheme(
        backgroundColor: Color(0xFF4C1D95),
        foregroundColor: Color(0xFFF3E8FF),
      ),
      textTheme: const TextTheme(
        bodyLarge: TextStyle(color: Color(0xFFF3E8FF)),
        bodyMedium: TextStyle(color: Color(0xFFF3E8FF)),
        bodySmall: TextStyle(color: Color(0xFFE879F9)),
      ),
      iconTheme: const IconThemeData(color: Color(0xFF8B5CF6)),
    ),

    'Winter': ThemeData(
      brightness: Brightness.light,
      scaffoldBackgroundColor: const Color(0xFFE0F2FE),
      primaryColor: const Color(0xFF0284C7),
      cardColor: const Color(0xFFBAE6FD),
      dividerColor: const Color(0xFF7DD3FC),
      hintColor: const Color(0xFF0369A1),
      colorScheme: const ColorScheme.light(
        primary: Color(0xFF0284C7),
        secondary: Color(0xFF7DD3FC),
        surface: Color(0xFFBAE6FD),
        background: Color(0xFFE0F2FE),
        onPrimary: Colors.white,
        onSecondary: Color(0xFF0C4A6E),
        onSurface: Color(0xFF0C4A6E),
        onBackground: Color(0xFF0C4A6E),
      ),
      appBarTheme: const AppBarTheme(
        backgroundColor: Color(0xFF0284C7),
        foregroundColor: Colors.white,
      ),
      textTheme: const TextTheme(
        bodyLarge: TextStyle(color: Color(0xFF0C4A6E)),
        bodyMedium: TextStyle(color: Color(0xFF0C4A6E)),
        bodySmall: TextStyle(color: Color(0xFF0369A1)),
      ),
      iconTheme: const IconThemeData(color: Color(0xFF0284C7)),
    ),

    'Dark Blue': ThemeData(
      brightness: Brightness.dark,
      scaffoldBackgroundColor: const Color(0xFF1E3A8A),
      primaryColor: const Color(0xFF3B82F6),
      cardColor: const Color(0xFF1E40AF),
      dividerColor: const Color(0xFF2563EB),
      hintColor: const Color(0xFF60A5FA),
      colorScheme: const ColorScheme.dark(
        primary: Color(0xFF3B82F6),
        secondary: Color(0xFF60A5FA),
        surface: Color(0xFF1E40AF),
        background: Color(0xFF1E3A8A),
        onPrimary: Colors.white,
        onSecondary: Color(0xFF1E3A8A),
        onSurface: Color(0xFFDBEAFE),
        onBackground: Color(0xFFDBEAFE),
      ),
      appBarTheme: const AppBarTheme(
        backgroundColor: Color(0xFF1E40AF),
        foregroundColor: Color(0xFFDBEAFE),
      ),
      textTheme: const TextTheme(
        bodyLarge: TextStyle(color: Color(0xFFDBEAFE)),
        bodyMedium: TextStyle(color: Color(0xFFDBEAFE)),
        bodySmall: TextStyle(color: Color(0xFF60A5FA)),
      ),
      iconTheme: const IconThemeData(color: Color(0xFF3B82F6)),
    ),

    'Sunset': ThemeData(
      brightness: Brightness.light,
      scaffoldBackgroundColor: const Color(0xFFFFEDD5),
      primaryColor: const Color(0xFFF97316),
      cardColor: const Color(0xFFFED7AA),
      dividerColor: const Color(0xFFFBBF24),
      hintColor: const Color(0xFFEA580C),
      colorScheme: const ColorScheme.light(
        primary: Color(0xFFF97316),
        secondary: Color(0xFFFBBF24),
        surface: Color(0xFFFED7AA),
        background: Color(0xFFFFEDD5),
        onPrimary: Colors.white,
        onSecondary: Color(0xFF92400E),
        onSurface: Color(0xFF92400E),
        onBackground: Color(0xFF92400E),
      ),
      appBarTheme: const AppBarTheme(
        backgroundColor: Color(0xFFF97316),
        foregroundColor: Colors.white,
      ),
      textTheme: const TextTheme(
        bodyLarge: TextStyle(color: Color(0xFF92400E)),
        bodyMedium: TextStyle(color: Color(0xFF92400E)),
        bodySmall: TextStyle(color: Color(0xFFEA580C)),
      ),
      iconTheme: const IconThemeData(color: Color(0xFFF97316)),
    ),

    'Royal': ThemeData(
      brightness: Brightness.dark,
      scaffoldBackgroundColor: const Color(0xFF0F172A),
      primaryColor: const Color(0xFF6366F1),
      cardColor: const Color(0xFF1E293B),
      dividerColor: const Color(0xFF334155),
      hintColor: const Color(0xFF818CF8),
      colorScheme: const ColorScheme.dark(
        primary: Color(0xFF6366F1),
        secondary: Color(0xFF818CF8),
        surface: Color(0xFF1E293B),
        background: Color(0xFF0F172A),
        onPrimary: Colors.white,
        onSecondary: Color(0xFF0F172A),
        onSurface: Color(0xFFF1F5F9),
        onBackground: Color(0xFFF1F5F9),
      ),
      appBarTheme: const AppBarTheme(
        backgroundColor: Color(0xFF1E293B),
        foregroundColor: Color(0xFFF1F5F9),
      ),
      textTheme: const TextTheme(
        bodyLarge: TextStyle(color: Color(0xFFF1F5F9)),
        bodyMedium: TextStyle(color: Color(0xFFF1F5F9)),
        bodySmall: TextStyle(color: Color(0xFF818CF8)),
      ),
      iconTheme: const IconThemeData(color: Color(0xFF6366F1)),
    ),

    'Neon': ThemeData(
      brightness: Brightness.dark,
      scaffoldBackgroundColor: const Color(0xFF111827),
      primaryColor: const Color(0xFF38BDF8),
      cardColor: const Color(0xFF1F2937),
      dividerColor: const Color(0xFF374151),
      hintColor: const Color(0xFFA855F7),
      colorScheme: const ColorScheme.dark(
        primary: Color(0xFF38BDF8),
        secondary: Color(0xFFA855F7),
        surface: Color(0xFF1F2937),
        background: Color(0xFF111827),
        onPrimary: Color(0xFF111827),
        onSecondary: Colors.white,
        onSurface: Color(0xFFF9FAFB),
        onBackground: Color(0xFFF9FAFB),
      ),
      appBarTheme: const AppBarTheme(
        backgroundColor: Color(0xFF1F2937),
        foregroundColor: Color(0xFFF9FAFB),
      ),
      textTheme: const TextTheme(
        bodyLarge: TextStyle(color: Color(0xFFF9FAFB)),
        bodyMedium: TextStyle(color: Color(0xFFF9FAFB)),
        bodySmall: TextStyle(color: Color(0xFFA855F7)),
      ),
      iconTheme: const IconThemeData(color: Color(0xFF38BDF8)),
    ),

    'Bubblegum': ThemeData(
      brightness: Brightness.light,
      scaffoldBackgroundColor: const Color(0xFFFFF0F6),
      primaryColor: const Color(0xFFF472B6),
      cardColor: const Color(0xFFFCE7F3),
      dividerColor: const Color(0xFFF9A8D4),
      hintColor: const Color(0xFFBE185D),
      colorScheme: const ColorScheme.light(
        primary: Color(0xFFF472B6),
        secondary: Color(0xFFF9A8D4),
        surface: Color(0xFFFCE7F3),
        background: Color(0xFFFFF0F6),
        onPrimary: Colors.white,
        onSecondary: Color(0xFF831843),
        onSurface: Color(0xFF831843),
        onBackground: Color(0xFF831843),
      ),
      appBarTheme: const AppBarTheme(
        backgroundColor: Color(0xFFF472B6),
        foregroundColor: Colors.white,
      ),
      textTheme: const TextTheme(
        bodyLarge: TextStyle(color: Color(0xFF831843)),
        bodyMedium: TextStyle(color: Color(0xFF831843)),
        bodySmall: TextStyle(color: Color(0xFFBE185D)),
      ),
      iconTheme: const IconThemeData(color: Color(0xFFF472B6)),
    ),
  };
}
